#!/bin/bash
#
# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

m finalize_res
finalize_res \
    "$top/frameworks/base/core/res/res/values/public-staging.xml" \
    "$top/frameworks/base/core/res/res/values/public-final.xml"

m update-api

git_commit \
    frameworks/base \
<<EOF
Finalize resources for Android $MAJOR.$MINOR

CL generated by running these commands:

  m finalize_res
  finalize_res \\
      \$(gettop)frameworks/base/core/res/res/values/public-staging.xml \\
      \$(gettop)frameworks/base/core/res/res/values/public-final.xml
  m update-api

EOF

# vi: expandtab sw=4 ts=4
