#!/bin/bash
#
# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
source "$(dirname "$0")"/common.sh

command="$1"
if [[ -z "$command" ]]; then
    error "missing command"
    exit 1
fi
shift
case "$command" in
    finalize-module-sdks)
        error "not yet implemented"
        exit 1
        ;;
    finalize-resources)
        error "not yet implemented"
        exit 1
        ;;
    finalize-ndk)
        error "not yet implemented"
        exit 1
        ;;
    finalize-platform-sdk)
        error "not yet implemented"
        exit 1
        ;;
    finalize-release-configs)
        error "not yet implemented"
        exit 1
        ;;
    *)
        error "unexpected command: $command"
        exit 1
        ;;
esac

# vi: expandtab sw=4 ts=4
