#!/bin/bash
#
# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
source "$(dirname "$0")"/common.sh
source "$(dirname "$0")"/config.sh

function require_arg() {
    local arg="$1"
    local value="${!2}"
    if [[ -z "$value" ]]; then
        error "missing $arg <value>"
        exit 1
    fi
}

command="$1"
if [[ -z "$command" ]]; then
    error "missing command"
    exit 1
fi
shift

patch_dir=""
mainline_sdks_dir=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --patch-dir)
            if [[ -z "$2" ]]; then
                error "--patch-dir: missing <value>"
                exit 1
            fi
            patch_dir="$(readlink -f "$2")"
            shift 2
            ;;
        --mainline-sdks-dir)
            if [[ -z "$2" ]]; then
                error "--mainline-sdks-dir: missing <value>"
                exit 1
            fi
            mainline_sdks_dir="$(readlink -f "$2")"
            shift 2
            ;;
    esac
done

case "$command" in
    finalize-module-sdks)
        require_arg "--mainline-sdks-dir" "mainline_sdks_dir"
        source "$(dirname "$0")"/finalize-module-sdks.sh
        ;;
    finalize-resources)
        source "$(dirname "$0")"/finalize-resources.sh
        ;;
    finalize-ndk)
        info "not yet implemented"
        ;;
    finalize-platform-sdk)
        source "$(dirname "$0")"/finalize-platform-sdk.sh
        ;;
    finalize-release-configs)
        error "not yet implemented"
        exit 1
        ;;
    apply-patches)
        require_arg "--patch-dir" "patch_dir"
        apply_patches_from_patchdir "$patch_dir"
        ;;
    format-patches)
        require_arg "--patch-dir" "patch_dir"
        format_patches_into_patchdir "$patch_dir"
        ;;
    setup-build-server)
        setup_build_server
        ;;
    *)
        error "unexpected command: $command"
        exit 1
        ;;
esac
